# -*- coding: utf-8 -*-
"""tds_8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QAq1lvQrL9CVQQvLWQI-b_wAwqfJXvow
"""

import streamlit as st

# Function to find the largest number
def find_largest(num1, num2, num3):
    return max(num1, num2, num3)

# Streamlit UI
st.title('Find the Largest Number')

# Set a finite range for the number inputs
min_value = -1e9  # Example minimum value
max_value = 1e9   # Example maximum value

num1 = st.number_input('Enter first number', min_value=min_value, max_value=max_value, step=1.0)
num2 = st.number_input('Enter second number', min_value=min_value, max_value=max_value, step=1.0)
num3 = st.number_input('Enter third number', min_value=min_value, max_value=max_value, step=1.0)

if st.button('Find Largest'):
    largest = find_largest(num1, num2, num3)
    st.write(f'The largest number is: {largest}')
